/mnt/localdrive/workspace-LPP/code/neurospin-petit-prince/decoding/cluster/dataset.py:51: RuntimeWarning: This file contains raw Internal Active Shielding data. It may be distorted. Elekta recommends it be run through MaxFilter to produce reliable results. Consider closing the file and running MaxFilter on the data.
  raw = mne_bids.read_raw_bids(bids_path)
/mnt/localdrive/workspace-LPP/code/neurospin-petit-prince/decoding/cluster/dataset.py:51: RuntimeWarning: Omitted 117 annotation(s) that were outside data range.
  raw = mne_bids.read_raw_bids(bids_path)
/mnt/localdrive/workspace-LPP/code/neurospin-petit-prince/decoding/cluster/dataset.py:51: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne_bids.read_raw_bids(bids_path)
/mnt/localdrive/workspace-LPP/code/neurospin-petit-prince/decoding/cluster/dataset.py:51: RuntimeWarning: The unit for channel(s) STI001, STI002, STI003, STI004, STI005, STI006, STI007, STI008, STI009, STI010, STI011, STI012, STI013, STI014, STI015, STI016, STI101, STI201, STI301 has changed from V to NA.
  raw = mne_bids.read_raw_bids(bids_path)
submitit ERROR (2023-04-25 13:40:50,922) - Submitted job triggered an exception
Traceback (most recent call last):
  File "/home/is153802/.pyenv/versions/3.10.6/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/is153802/.pyenv/versions/3.10.6/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/is153802/.pyenv/versions/meg-masc/lib/python3.10/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/home/is153802/.pyenv/versions/meg-masc/lib/python3.10/site-packages/submitit/core/submission.py", line 72, in submitit_main
    process_job(args.folder)
  File "/home/is153802/.pyenv/versions/meg-masc/lib/python3.10/site-packages/submitit/core/submission.py", line 65, in process_job
    raise error
  File "/home/is153802/.pyenv/versions/meg-masc/lib/python3.10/site-packages/submitit/core/submission.py", line 54, in process_job
    result = delayed.result()
  File "/home/is153802/.pyenv/versions/meg-masc/lib/python3.10/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/tmp/ipykernel_200815/751625764.py", line 31, in analysis
  File "/mnt/localdrive/workspace-LPP/code/neurospin-petit-prince/decoding/cluster/dataset.py", line 80, in read_raw
    assert len(i) > (0.9 * len(events))
AssertionError
